name: Continuous Integration

on:
  workflow_dispatch:
    inputs:
      input-json:
        description: JSON of inputs
        type: string
        default: '{}'
        required: true

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          # Source Inputs
          source-domain: ${{ fromJson(inputs.input-json).source-domain }}
          source-project-id:
            ${{ fromJson(inputs.input-json).source-project-id }}
          source-resources: ${{ fromJson(inputs.input-json).source-resources }}
          # Flow Inputs
          source-flow-names:
            ${{ fromJson(inputs.input-json).source-flow-names }}
          source-flow-stage:
            ${{ fromJson(inputs.input-json).source-flow-stage }}
          # Connector Inputs
          source-connector-org-id:
            ${{ fromJson(inputs.input-json).source-connector-org-id }}
          source-connector-group-ids:
            ${{ fromJson(inputs.input-json).source-connector-group-ids }}
          source-connector-ids:
            ${{ fromJson(inputs.input-json).source-connector-ids }}
          # Model Inputs
          source-model-ids: ${{ fromJson(inputs.input-json).source-model-ids }}
          # Template Inputs
          source-template-ids:
            ${{ fromJson(inputs.input-json).source-template-ids }}
          source-template-org-id:
            ${{ fromJson(inputs.input-json).source-template-org-id }}
          # Webhook Inputs
          source-webhook-ids:
            ${{ fromJson(inputs.input-json).source-webhook-ids }}
          # Widget Inputs
          source-widget-ids:
            ${{ fromJson(inputs.input-json).source-widget-ids }}
          # Source Auth
          source-account-username:
            ${{ fromJson(inputs.input-json).source-account-username }}
          source-account-password:
            ${{ fromJson(inputs.input-json).source-account-password }}
          # Destination Domain
          destination-domain:
            ${{ fromJson(inputs.input-json).destination-domain }}
          destination-project-id:
            ${{ fromJson(inputs.input-json).destination-project-id }}
          # Flow Inputs
          destination-flow-stage:
            ${{ fromJson(inputs.input-json).destination-flow-stage }}
          # Connector Inputs
          destination-connector-org-id:
            ${{ fromJson(inputs.input-json).destination-connector-org-id }}
          # Template Inputs
          destination-template-org-id:
            ${{ fromJson(inputs.input-json).destination-template-org-id }}
          # Destination Auth
          destination-account-username:
            ${{ fromJson(inputs.input-json).destination-account-username }}
          destination-account-password:
            ${{ fromJson(inputs.input-json).destination-account-password }}
